create table if not exists public.lowongan_pekerjaan (
  id bigint generated by default as identity primary key,
  kebutuhan_id bigint null references public.kebutuhan_karyawan(id) on delete set null,
  judul_lowongan text not null,
  posisi text not null,
  departemen text null,
  cabang text null,
  company_name text null,
  jumlah_kebutuhan integer null default 1,
  status_kerja text null,
  tipe_kerja text null,
  durasi_kontrak text null,
  gaji_min bigint null,
  gaji_max bigint null,
  pendidikan_min text null,
  pengalaman text null,
  skill text[] not null default '{}',
  skill_text text null,
  kriteria_tambahan text null,
  tes_yang_diperlukan text[] not null default '{}',
  deskripsi_pekerjaan text null,
  ringkasan_iklan text null,
  tanggung_jawab text null,
  tentang_perusahaan text null,
  lokasi_kerja text null,
  benefit text null,
  cara_melamar text null,
  status_lowongan text not null default 'Belum tayang',
  tanggal_tayang date null,
  tanggal_tutup date null,
  applicants_count integer not null default 0,
  source_type text null default 'manual',
  person_in_charge text null,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lowongan_pekerjaan_kebutuhan_id_idx
  on public.lowongan_pekerjaan (kebutuhan_id);

create index if not exists lowongan_pekerjaan_status_lowongan_idx
  on public.lowongan_pekerjaan (status_lowongan);

create index if not exists lowongan_pekerjaan_archived_idx
  on public.lowongan_pekerjaan (archived);

create or replace function public.set_lowongan_pekerjaan_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_lowongan_pekerjaan_updated_at on public.lowongan_pekerjaan;

create trigger trg_lowongan_pekerjaan_updated_at
before update on public.lowongan_pekerjaan
for each row
execute function public.set_lowongan_pekerjaan_updated_at();
