create table if not exists public.pelamar (
  id bigint generated by default as identity primary key,
  lowongan_id bigint references public.lowongan_pekerjaan(id) on delete set null,
  posisi_dilamar text not null,
  sumber_info_lowongan text,
  nama_lengkap text not null,
  email text not null,
  no_hp text not null,
  tanggal_lahir date not null,
  agama text,
  status_pernikahan text,
  jenis_kelamin text not null,
  kewarganegaraan text,
  alamat_ktp text not null,
  alamat_domisili text not null,
  institusi_pendidikan text,
  jenjang_pendidikan text,
  jurusan text,
  tahun_lulus text,
  ipk_nilai text,
  fresh_graduate boolean not null default false,
  lama_pengalaman_tahun text,
  pengalaman_list jsonb not null default '[]'::jsonb,
  pengalaman_utama_perusahaan text,
  pengalaman_utama_jabatan text,
  pengalaman_utama_tanggal_masuk date,
  pengalaman_utama_tanggal_keluar date,
  pengalaman_utama_masih_kerja boolean not null default false,
  pengalaman_utama_deskripsi text,
  pengalaman_utama_alasan_resign text,
  ekspektasi_gaji bigint,
  masa_notice text,
  cv_file_name text not null,
  status_tindak_lanjut text not null default 'Baru masuk',
  tahap_proses text not null default 'Seleksi awal',
  penilaian_singkat text,
  catatan_recruiter text,
  interview_datetime timestamptz,
  interview_location text,
  interview_interviewer text,
  interview_notes text,
  archived boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists pelamar_lowongan_id_idx
  on public.pelamar (lowongan_id);

create index if not exists pelamar_status_tindak_lanjut_idx
  on public.pelamar (status_tindak_lanjut);

create index if not exists pelamar_tahap_proses_idx
  on public.pelamar (tahap_proses);

create index if not exists pelamar_archived_idx
  on public.pelamar (archived);

create index if not exists pelamar_created_at_idx
  on public.pelamar (created_at desc);

create or replace function public.set_pelamar_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_pelamar_updated_at on public.pelamar;

create trigger trg_pelamar_updated_at
before update on public.pelamar
for each row
execute function public.set_pelamar_updated_at();
