export interface Pelamar {
  id: number;
  lowongan_id: number | null;
  posisi_dilamar: string;
  sumber_info_lowongan: string | null;
  nama_lengkap: string;
  email: string;
  no_hp: string;
  tanggal_lahir: string;
  agama: string | null;
  status_pernikahan: string | null;
  jenis_kelamin: string;
  kewarganegaraan: string | null;
  alamat_ktp: string;
  alamat_domisili: string;
  institusi_pendidikan: string | null;
  jenjang_pendidikan: string | null;
  jurusan: string | null;
  tahun_lulus: string | null;
  ipk_nilai: string | null;
  fresh_graduate: boolean;
  lama_pengalaman_tahun: string | null;
  pengalaman_list: Array<Record<string, unknown>>;
  pengalaman_utama_perusahaan: string | null;
  pengalaman_utama_jabatan: string | null;
  pengalaman_utama_tanggal_masuk: string | null;
  pengalaman_utama_tanggal_keluar: string | null;
  pengalaman_utama_masih_kerja: boolean;
  pengalaman_utama_deskripsi: string | null;
  pengalaman_utama_alasan_resign: string | null;
  ekspektasi_gaji: number | null;
  masa_notice: string | null;
  cv_file_name: string;
  status_tindak_lanjut: string;
  tahap_proses: string;
  penilaian_singkat: string | null;
  catatan_recruiter: string | null;
  last_contacted_at: string | null;
  alasan_tidak_lanjut: string | null;
  interview_datetime: string | null;
  interview_location: string | null;
  interview_interviewer: string | null;
  interview_notes: string | null;
  archived: boolean;
  created_at: string;
  updated_at: string;
}

export type CreatePelamarPayload = Omit<Pelamar, "id" | "created_at" | "updated_at">;
export type UpdatePelamarPayload = Partial<Omit<Pelamar, "id" | "created_at" | "updated_at">>;
