create table if not exists public.review_seleksi_awal (
  id bigint generated by default as identity primary key,
  pelamar_id bigint not null references public.pelamar(id) on delete cascade,
  status_review text not null,
  fit_level text,
  ringkasan_review text,
  catatan_recruiter text,
  alasan_tidak_lanjut text,
  reviewed_by text,
  reviewed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists review_seleksi_awal_pelamar_id_idx
  on public.review_seleksi_awal (pelamar_id, reviewed_at desc);
