alter table if exists public.hr_contracts
  add column if not exists template_name text not null default 'Template standar kontrak',
  add column if not exists article_clauses jsonb not null default '[]'::jsonb;

create table if not exists public.hr_contract_templates (
  id bigint generated by default as identity primary key,
  template_name text not null unique,
  description text not null default '',
  article_clauses jsonb not null default '[]'::jsonb,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_hr_contract_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_hr_contract_templates_updated_at on public.hr_contract_templates;

create trigger trg_hr_contract_templates_updated_at
before update on public.hr_contract_templates
for each row
execute function public.set_hr_contract_templates_updated_at();
