create table if not exists public.hr_offboarding_processes (
  id bigint generated by default as identity primary key,
  source_employee_row_id bigint references public.employees(id) on delete set null,
  employee_code text not null,
  employee_name text not null,
  job_title text not null default '-',
  division_name text not null default '-',
  business_name text not null default 'Perusahaan',
  branch_name text not null default '-',
  exit_reason text not null default '-',
  exit_request_date date,
  last_working_date date,
  supervisor_approval text not null default 'Menunggu persetujuan',
  process_status text not null default 'Akan keluar',
  asset_status text not null default 'Belum kembali',
  access_status text not null default 'Belum ditutup',
  final_document_status text not null default 'Belum dibuat',
  certificate_ready boolean not null default false,
  handover_report_ready boolean not null default false,
  employee_deactivated boolean not null default false,
  owner_name text not null default 'Tim HR',
  hr_note text not null default '',
  asset_note text not null default '',
  access_note text not null default '',
  final_letter_note text not null default '',
  checklist jsonb not null default '[]'::jsonb,
  linked_modules jsonb not null default '[]'::jsonb,
  needs_attention boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists hr_offboarding_processes_employee_code_last_working_date_key
  on public.hr_offboarding_processes (employee_code, last_working_date);

create index if not exists hr_offboarding_processes_process_status_idx
  on public.hr_offboarding_processes (process_status);

create index if not exists hr_offboarding_processes_last_working_date_idx
  on public.hr_offboarding_processes (last_working_date desc nulls last);

create index if not exists hr_offboarding_processes_created_at_idx
  on public.hr_offboarding_processes (created_at desc);

create or replace function public.set_hr_offboarding_processes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_hr_offboarding_processes_updated_at on public.hr_offboarding_processes;

create trigger trg_hr_offboarding_processes_updated_at
before update on public.hr_offboarding_processes
for each row
execute function public.set_hr_offboarding_processes_updated_at();
