alter table public.pelamar
  add column if not exists last_contacted_at timestamptz,
  add column if not exists alasan_tidak_lanjut text;

create table if not exists public.riwayat_tahap_pelamar (
  id bigint generated by default as identity primary key,
  pelamar_id bigint not null references public.pelamar(id) on delete cascade,
  dari_tahap text,
  ke_tahap text not null,
  catatan text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists riwayat_tahap_pelamar_pelamar_id_idx
  on public.riwayat_tahap_pelamar (pelamar_id, created_at desc);

create table if not exists public.jadwal_wawancara (
  id bigint generated by default as identity primary key,
  pelamar_id bigint not null references public.pelamar(id) on delete cascade,
  interview_datetime timestamptz not null,
  interviewer text not null,
  location text not null,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists jadwal_wawancara_pelamar_id_idx
  on public.jadwal_wawancara (pelamar_id, interview_datetime desc);

create or replace function public.set_jadwal_wawancara_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_jadwal_wawancara_updated_at on public.jadwal_wawancara;

create trigger trg_jadwal_wawancara_updated_at
before update on public.jadwal_wawancara
for each row
execute function public.set_jadwal_wawancara_updated_at();
