create table if not exists public.offering_letters (
  id bigint generated by default as identity primary key,
  pelamar_id bigint not null references public.pelamar(id) on delete cascade,
  status text not null default 'draft',
  version integer not null default 1,
  position_title text,
  branch_name text,
  company_name text,
  employment_type text,
  salary_amount bigint,
  start_date date,
  probation_period text,
  benefits_summary text,
  response_deadline date,
  hr_pic_name text,
  additional_notes text,
  letter_payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  responded_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists offering_letters_pelamar_id_idx
  on public.offering_letters (pelamar_id, created_at desc);

create index if not exists offering_letters_status_idx
  on public.offering_letters (status, updated_at desc);

create unique index if not exists offering_letters_one_active_per_pelamar_idx
  on public.offering_letters (pelamar_id)
  where status in ('draft', 'waiting_response', 'negotiation', 'accepted');

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'offering_letters_status_check'
  ) then
    alter table public.offering_letters
      add constraint offering_letters_status_check
      check (status in ('draft', 'waiting_response', 'negotiation', 'accepted', 'rejected', 'expired'));
  end if;
end
$$;

create or replace function public.set_offering_letters_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_offering_letters_updated_at on public.offering_letters;

create trigger trg_offering_letters_updated_at
before update on public.offering_letters
for each row
execute function public.set_offering_letters_updated_at();
