create table if not exists public.hr_contracts (
  id bigint generated by default as identity primary key,
  source_employee_row_id bigint references public.employees(id) on delete set null,
  employee_code text not null,
  employee_name text not null,
  job_title text not null default '-',
  division_name text not null default '-',
  business_name text not null default 'Perusahaan',
  branch_name text not null default '-',
  employment_status text not null default 'Kontrak',
  contract_number text not null,
  contract_type text not null default '-',
  start_date date,
  end_date date,
  contract_months integer not null default 0,
  base_salary text not null default '-',
  main_allowance text not null default '-',
  contract_file text not null default 'Belum ada file',
  contract_status text not null default 'Belum dibuat',
  signing_status text not null default 'Belum ditandatangani',
  review_date date,
  next_decision text not null default 'Masih dipertimbangkan',
  owner_name text not null default 'Tim HR',
  hr_note text not null default '',
  reminder text not null default '',
  needs_attention boolean not null default false,
  linked_modules jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists hr_contracts_contract_number_key
  on public.hr_contracts (contract_number);

create index if not exists hr_contracts_employee_code_idx
  on public.hr_contracts (employee_code);

create index if not exists hr_contracts_contract_status_idx
  on public.hr_contracts (contract_status);

create index if not exists hr_contracts_end_date_idx
  on public.hr_contracts (end_date desc nulls last);

create or replace function public.set_hr_contracts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_hr_contracts_updated_at on public.hr_contracts;

create trigger trg_hr_contracts_updated_at
before update on public.hr_contracts
for each row
execute function public.set_hr_contracts_updated_at();
