create table if not exists public.probation_reviews (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  review_code text not null unique,
  status_review text not null default 'Belum dimulai',
  decision text,
  start_date date,
  end_date date,
  evaluation_date date,
  extension_end_date date,
  evaluator_name text,
  evaluator_role text,
  attendance_score text,
  attitude_score text,
  task_understanding_score text,
  work_quality_score text,
  responsibility_score text,
  teamwork_score text,
  strengths_note text,
  coaching_note text,
  evaluator_note text,
  decision_note text,
  decided_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists probation_reviews_employee_id_idx
  on public.probation_reviews (employee_id);

create index if not exists probation_reviews_status_review_idx
  on public.probation_reviews (status_review, evaluation_date);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'probation_reviews_status_review_check'
  ) then
    alter table public.probation_reviews
      add constraint probation_reviews_status_review_check
      check (status_review in ('Belum dimulai', 'Sedang berjalan', 'Perlu dinilai', 'Selesai', 'Diperpanjang', 'Tidak dilanjutkan'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'probation_reviews_decision_check'
  ) then
    alter table public.probation_reviews
      add constraint probation_reviews_decision_check
      check (decision in ('Lulus', 'Perpanjang', 'Tidak dilanjutkan') or decision is null);
  end if;
end
$$;

create or replace function public.set_probation_reviews_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_probation_reviews_updated_at on public.probation_reviews;

create trigger trg_probation_reviews_updated_at
before update on public.probation_reviews
for each row
execute function public.set_probation_reviews_updated_at();
