create table if not exists public.candidate_test_packages (
  id bigint generated by default as identity primary key,
  pelamar_id bigint not null references public.pelamar(id) on delete cascade,
  template_key text not null,
  template_name text not null,
  status text not null default 'sent',
  link_token text not null unique,
  link_url text,
  sent_at timestamptz,
  opened_at timestamptz,
  completed_at timestamptz,
  reviewed_at timestamptz,
  deadline_at timestamptz,
  created_by text,
  catatan_recruiter text,
  overall_summary text,
  overall_recommendation text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.candidate_test_package_items (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.candidate_test_packages(id) on delete cascade,
  test_key text not null,
  test_name_snapshot text not null,
  test_order integer not null default 1,
  status text not null default 'pending',
  started_at timestamptz,
  completed_at timestamptz,
  score_numeric numeric,
  score_label text,
  summary text,
  result_json jsonb not null default '{}'::jsonb,
  test_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists candidate_test_packages_pelamar_id_idx
  on public.candidate_test_packages (pelamar_id);

create index if not exists candidate_test_packages_status_idx
  on public.candidate_test_packages (status);

create index if not exists candidate_test_packages_is_active_idx
  on public.candidate_test_packages (is_active);

create index if not exists candidate_test_package_items_package_id_idx
  on public.candidate_test_package_items (package_id);

create index if not exists candidate_test_package_items_status_idx
  on public.candidate_test_package_items (status);

create unique index if not exists candidate_test_packages_one_active_per_pelamar_idx
  on public.candidate_test_packages (pelamar_id)
  where is_active = true;

create or replace function public.set_candidate_test_packages_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_candidate_test_packages_updated_at on public.candidate_test_packages;

create trigger trg_candidate_test_packages_updated_at
before update on public.candidate_test_packages
for each row
execute function public.set_candidate_test_packages_updated_at();

create or replace function public.set_candidate_test_package_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_candidate_test_package_items_updated_at on public.candidate_test_package_items;

create trigger trg_candidate_test_package_items_updated_at
before update on public.candidate_test_package_items
for each row
execute function public.set_candidate_test_package_items_updated_at();
