create table if not exists public.probation_decision_history (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees (id) on delete cascade,
  probation_review_id bigint references public.probation_reviews (id) on delete set null,
  decision text,
  status_review text,
  decision_note text,
  effective_date date,
  created_by text,
  created_role text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists probation_decision_history_employee_idx
  on public.probation_decision_history (employee_id, created_at desc);

create index if not exists probation_decision_history_review_idx
  on public.probation_decision_history (probation_review_id, created_at desc);
