create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  source_pelamar_id bigint references public.pelamar(id) on delete set null,
  employee_id text not null,
  nik text,
  nama_lengkap text not null,
  nama_panggilan text,
  jabatan text not null default '-',
  departemen text not null default '-',
  status_kerja text not null default 'Probation',
  tanggal_masuk date,
  cabang text not null default '-',
  status_karyawan text not null default 'Aktif',
  nama_usaha text not null default 'Perusahaan',
  atasan text not null default '-',
  tipe_kontrak text not null default '-',
  lokasi_kerja text,
  shift text,
  jenis_kelamin text,
  agama text,
  tempat_lahir text,
  status_pernikahan text,
  tanggal_lahir date,
  kewarganegaraan text,
  golongan_darah text,
  no_ktp text,
  no_kk text,
  npwp text,
  bpjs_kesehatan text,
  bpjs_ketenagakerjaan text,
  passport text,
  no_hp text,
  email_pribadi text,
  email_kantor text,
  alamat_ktp text,
  alamat_domisili text,
  kota text,
  provinsi text,
  kode_pos text,
  kontak_darurat text,
  pendidikan jsonb not null default '[]'::jsonb,
  keluarga jsonb not null default '[]'::jsonb,
  dokumen jsonb not null default '[]'::jsonb,
  change_history jsonb not null default '[]'::jsonb,
  status_overview jsonb not null default '{"dataLengkap":0,"dokumenTerunggah":0,"dataPerluDiperbarui":0,"menungguVerifikasiHr":0,"checklist":[]}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists employees_employee_id_key
  on public.employees (employee_id);

create unique index if not exists employees_source_pelamar_id_key
  on public.employees (source_pelamar_id)
  where source_pelamar_id is not null;

create index if not exists employees_tanggal_masuk_idx
  on public.employees (tanggal_masuk desc);

create index if not exists employees_status_karyawan_idx
  on public.employees (status_karyawan);

create index if not exists employees_created_at_idx
  on public.employees (created_at desc);

create or replace function public.set_employees_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_employees_updated_at on public.employees;

create trigger trg_employees_updated_at
before update on public.employees
for each row
execute function public.set_employees_updated_at();
